package de.uniba.dsg.serverless.cli;

import de.uniba.dsg.serverless.ArgumentProcessor;
import de.uniba.dsg.serverless.benchmark.logs.aws.AWSLogHandler;
import de.uniba.dsg.serverless.model.SeMoDeException;
import de.uniba.dsg.serverless.util.FileLogger;

import java.time.LocalDateTime;
import java.util.List;

/**
 * This is the main class for starting the analysis process and generating test
 * classes. The command line arguments are as follows: <br/>
 * <b>(1)</b> Region, e.g. \"eu-west-1\" <br/>
 * <b>(2)</b> LogGroupName <br/>
 * <b>(3)</b> search string, e.g. "Exception" to tackle java exception <br/>
 */
@Deprecated
public final class SeMoDeUtility extends CustomUtility {

    private static final FileLogger logger = ArgumentProcessor.logger;

    public SeMoDeUtility(final String name) {
        super(name);
    }

    @Override
    public void start(final List<String> args) {

        if (args.size() < 5) {
            logger.warning("Wrong parameter size: \n(1) Region, e.g. \"eu-west-1\" - " + "\n(2) LogGroupName "
                    + "\n(3) search string, e.g. \"exception\" to tackle java exception" + "\n(4) Start time filter "
                    + "\n(5) End time filter ");
            return;
        }

        final String region = args.get(0);
        final String logGroupName = args.get(1);
        final String searchString = args.get(2);
        final String startTimeString = args.get(3);
        final String endTimeString = args.get(4);

        try {
            this.validateStartEnd(startTimeString, endTimeString);

            final LocalDateTime startTime = this.parseTime(startTimeString);
            final LocalDateTime endTime = this.parseTime(endTimeString);

            logger.info("Region: " + region + "\tLogGroupName: " + logGroupName + "\tSearch string: " + searchString);
            new AWSLogHandler(region, logGroupName, startTime, endTime).startAnalzying(searchString);
        } catch (final SeMoDeException e) {
            logger.warning(e.getMessage());
        }
    }
}

//import java.io.IOException;
//
//		import org.junit.Assert;
//		import org.junit.BeforeClass;
//		import org.junit.Test;
//		import com.fasterxml.jackson.databind.ObjectMapper;
///**
// *  This is a generated test class for a error occurred during operations.
// *  Generated by: SeMoDe Protoype
// *
// */
//
///**
// * The log data from the AWS Cloud Watch console:
// FUNCTION_LOG
// */
//public class FILENAME {
//
//	private static INPUTCLASS input;
//
//	@BeforeClass
//	public static void createInput() throws IOException {
//		String jsonInput = INPUTJSON;
//		input = new ObjectMapper().readValue(jsonInput, INPUTCLASS.class);
//	}
//
//	@Test
//	public void testLambdaFunctionHandler() {
//		HANDLERCLASS handler = new HANDLERCLASS();
//
//		OUTPUTCLASS output = handler.HANDLERMETHOD(input, null);
//
//		// TODO: validate output here
//		Assert.assertEquals(??, output);
//	}
//}
