#!/bin/bash
PACKAGES_DIR=deployment-packages
DEPLOYMENT_DIR=deployment
PACKAGE_SIZES=(3125000 6250000 12500000 25000000 50000000 100000000 200000000 400000000)
SERVICE_SIZES=(initial 3125000 6250000 12500000 25000000 50000000 100000000 200000000 400000000)

if [ -z "$1" ]; then
    echo "Usage: createDeployments <PATH_TO_SEMODE.JAR>"
    exit 1
fi

function createDir() {
    if [ ! -d "$1" ]; then
        mkdir -p "$1"
    fi
}

function createDeploymentSizes() {
    createDir "${PACKAGES_DIR}"

    # copy initial
    cp "fibonacci.js" "${PACKAGES_DIR}/fibonacci-js-initial.js"

    # other sizes
    echo " "
    before="initial"
    for size in ${PACKAGE_SIZES[@]}; do
        echo "Create deployment package size: ${size}"
        echo "..."
        cp "${PACKAGES_DIR}/fibonacci-js-${before}.js" "${PACKAGES_DIR}/fibonacci-js-${size}.js"
        java -jar "$1" "deploymentSize" "${PACKAGES_DIR}/fibonacci-js-${size}.js" "${size}" "//"
        echo "Done"
        echo " "
        before="${size}"
    done
}

function createServices() {
    for size in ${SERVICE_SIZES[@]}; do
        echo "Create function: size=${size}"

        serviceDir="${DEPLOYMENT_DIR}/fibonacci-js-${size}"

        createDir "${serviceDir}"
        cp "${PACKAGES_DIR}/fibonacci-js-${size}.js" "${serviceDir}/fibonacci.js"
        cp "serverless-template.yml" "${serviceDir}/serverless.yml"

        addFunctionToServerlessConfig "${size}" "${serviceDir}"
    done
}

function addFunctionToServerlessConfig() {
    size="$1"
    serviceDir="$2"

    function="  fibonacci-js-${size}:
    handler: fibonacci.handler
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res"

    echo "service: fibonacci-js-${size}" >> "${serviceDir}/serverless.yml" 
    echo "functions:" >> "${serviceDir}/serverless.yml"
    echo "${function}" >> "${serviceDir}/serverless.yml"
}

createDeploymentSizes "$1"
createServices
