#!/bin/bash
DEPLOYMENT_DIR=deployment
cd "${DEPLOYMENT_DIR}"

for service in *; do
    if [ -d "${service}" ]; then
        echo "Undeploy function: ${service}"
        cd "${service}"
        serverless remove
        cd ..
        echo " "
    fi
done
