#!/bin/bash
DEPLOYMENT_DIR=deployment
cd "${DEPLOYMENT_DIR}"

for service in *; do
    if [ -d "${service}" ]; then
        echo "Deploy function: ${service}"
        cd "${service}"
        mvn azure-functions:deploy
        cd ..
        echo " "
    fi
done
