#!/bin/bash

DIR=deployment
sizes=(1000000 2000000)

if [ -z "$1" ]; then
	echo "Usage: createDeploymentSizes <PATH_TO_SEMODE.JAR>"
	exit 1
fi

function createDir() {
    if [ ! -d "$1" ]; then
        mkdir -p "$1"
    fi
}

# Create Template
echo "Creating Template ..."
createDir "$DIR/fibonacci-java-initial/src/"
cp -rf "src/main/" "$DIR/fibonacci-java-initial/src/main/"
cp "pom.xml" "$DIR/fibonacci-java-initial/pom.xml"
echo "done"

# Copy Template to different sizes
echo "Building deployment packages using initial ..."
for size in ${sizes[@]}; do
	echo "Building deployment package fibonacci-java-${size}:"
	cp -rf "$DIR/fibonacci-java-initial/" "$DIR/fibonacci-java-${size}/"
	
	# 19 specifies the line that will be changed in the pom.xml
	# syntax:	sed -i "LINE_NUMBERs/.*/NEW_TEXT/
	sed -i '' "19s/.*/        <functionAppName>fibonacci-java-${size}<\/functionAppName>/" "$DIR/fibonacci-java-${size}/pom.xml"	
	mvn -f "$DIR/fibonacci-java-${size}/pom.xml" clean package
done
echo "Built all deployment packages"

# May be optimized, but it is not certain whether or not the integrity is compromised when jars are copied from other sizes
echo "Inflating the size of each deployment package"
for size in ${sizes[@]}; do
	echo "Create deployment package size: ${size}"
	java -jar "$1" "deploymentSize" "$DIR/fibonacci-java-${size}/target/azure-functions/fibonacci-java-${size}/azure-fibonacci-java-1.0.0.jar" "${size}"
done
echo "Extended the size of deployments"
