#!/bin/bash
DIR=deployment
sizes=(10000000 20000000 30000000 40000000 50000000)

if [ -z "$1" ]; then
    echo "Usage: createDeploymentSizes <PATH_TO_SEMODE.JAR>"
    exit 1
fi

if [ ! -d "$DIR" ]; then
    mkdir -p "$DIR"
fi

# initial size
before="initial"
cp "target/azure-fibonacci-java-1.0.0.jar" "$DIR/fibonacci-java-initial.jar"

echo " "
for size in ${sizes[@]}; do
    echo "Create deployment package size: ${size}"
    echo "..."
    cp "$DIR/fibonacci-java-${before}.jar" "$DIR/fibonacci-java-${size}.jar"
    java -jar "$1" "deploymentSize" "$DIR/fibonacci-java-${size}.jar" "$size"
    echo "Done"
    echo " "
    before="$size"
done
