#!/bin/bash
DEPLOYMENT_DIR=deployment
REGION=europe-west1
PROJECT=cloudfunctionsdsg
cd "${DEPLOYMENT_DIR}"

for service in *; do
    if [ -d "${service}" ]; then
        echo "Deploy function: ${service}"
        cd "${service}"
        serverless deploy
        cd ..
        echo "  GET - https://${REGION}-${PROJECT}.cloudfunctions.net/${service}"
        echo " "
    fi
done
