#!/bin/bash
DIR=deployment
sizes=(5000000 10000000 20000000 40000000 80000000 160000000 320000000 640000000)

if [ -z "$1" ]; then
    echo "Usage: createDeploymentSizes <PATH_TO_SEMODE.JAR>"
    exit 1
fi

if [ ! -d "$DIR" ]; then
    mkdir -p "$DIR"
fi

# initial size
cp "fibonacci.js" "$DIR/fibonacci-initial.js"

echo " "
for size in ${sizes[@]}; do
    echo "Create deployment package size: ${size}"
    echo "..."
    cp "fibonacci.js" "$DIR/fibonacci-${size}.js"
    java -jar "$1" "deploymentSize" "$DIR/fibonacci-${size}.js" "$size" "//"
    echo "Done"
    echo " "
done
